[package]
name = "generic-tests"
version = "0.1.0-dev"
authors = ["Mikhail Zabaluev <mikhail.zabaluev@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true
path = "src/macro.rs"

[features]
test-compile-fail = []

[dependencies]
syn = { version = "1.0", features = ["full", "visit-mut"] }
proc-macro2 = "1.0"
quote = "1.0"
